### ISSUE TITLE
Create a Settings Page

### ISSUE THREAD

**Issue by matthewdorman** [ndevrinc/project-dashboard#3]
Need a place to store things like API keys, what services to use and more.

**Comment by meekyhwang** [comment]
is this setting page per project content type or project dashboard? 
currently http://local.ndevr.io/wp-admin/project_dashboard which seems to be the project dashboard settings page is 404'ing for me.

**Comment by matthewdorman** [comment]
Yeah, I wasn't sure what we'd use that top level for... maybe a WordPress "dashboard" of some kind for the projects...  The "Settings" sub menu is the only one working at the moment, and that's for maintaining global settings for any of the sub modules we add like Browserstack, Slack, New Relic etc.

**Comment by meekyhwang** [comment]
ok. i will take a look.
